info:
  contact: {}
paths:
  /api/ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Vdm api status
swagger: "2.0"
